plugins:
  babble_enabled:
    default: true
    client: true
  babble_placeholder:
    default: ""
    client: true
  babble_icon:
    default: "bullhorn"
    client: true
  babble_page_size:
    default: 100
    client: true
  babble_position:
    default: left
    enum: 'Babble::PositionOptions'
    client: true
  babble_adaptive_height:
    default: false
    client: true
  babble_history_window:
    default: 0
  babble_open_by_default:
    default: false
    client: true
