plugins:
  babble_enabled:
    default: true
    client: true
  babble_placeholder:
    default: ""
    client: true
  babble_icon:
    default: "bullhorn"
    client: true
  babble_max_topic_size:
    default: 200
  babble_user_id:
    default: -2
    hidden: true
  babble_user_email:
    default: khattycathy@gmail.com
    hidden: true
  babble_username:
    default: chattykathy
    hidden: true
  babble_category_name:
    default: chat
